### PR TITLE
QCon talk blog post

### PR DESCRIPTION
**Pull request by mattwynne**
TODO:
- [x] add pictures
- [x] get feedback (preview [here](https://cucumber-website-pr-133.herokuapp.com/blog/2016/03/31/far-from-the-mobbing-crowd))
- [x] iterate on feedback
- [x] change the title?

### CODE REVIEW

**Comment by theo-england** [comment]
Great job. Feels like a really rich story, well worth sharing. 

I made some very minor typo edits in a separate PR (I guess I shouldn't have bothered creating a new one, apologies). 

I think it would be good to link to our training - perhaps with an ending call to action flourish.

Title suggestions - perhaps something a bit more straightforward for google?
- Our Mob Programming Story
- How to guide: mob programming
- The Cucumber guidebook to mob programming
- How we use mob programming
- My city mobbin in the street  - (Kendrick Lamar reference :-D)

Theo

**Comment by mattwynne** [comment]
It's long. As I read it back I'm wondering whether I can split it into two - one about mobbing and one that's more of a company story / what we learned from v1. WDYT @theo-england?

**Comment by mattwynne** [comment]
@theo-england I've given it a going-over and pulled out a lot of the detail about mobbing practices (I can use that content for another post). Can you read over it now and tell me what you think?

**Comment by mattwynne** [comment]
@theo-england preview is here: https://cucumber-website-pr-133.herokuapp.com/blog/2016/05/23/cucumber-ltd-story-so-far

**Comment by mattwynne** [comment]
OK @theo-england I reckon this is good enough to ship. Feel free to release it when you're ready.

**Comment by theo-england** [comment]
Will release after lunch. Nice work!

**Comment by aslakhellesoy** [comment]
Excellent post @mattwynne. That paints a good picture of what it's like here!

**Pull request merged**
