### PR TITLE
BDD for busy people questions blog

### PR DESCRIPTION
**Pull request by theo-england**

### CODE REVIEW

**Comment by mattwynne** [comment]
@theo-england I believe Google's algorithms look favourably upon us if we link to the original post in our copy. If they see us posting copies of other peoples content without attribution, they may down-grade us as a reliable source.

Just add a paragraph at the bottom saying "This article was originally posted here" with a link to the AWA blog post.

**Comment by tooky** [comment]
I think that link should be rel=canonical as well...

Maybe we could add a field to the metadata that does this automatically?

https://blog.kissmetrics.com/myths-about-duplicate-content/

**Comment by mattwynne** [comment]
@theo-england did you work out how to do this? Shout if you want a hand.

**Comment by theo-england** [comment]
@mattwynne I added the AWA link to the top, but didn't manage the "rel=canonical" bit. Wasn't sure how to do this in markdown. Trial and error by pull request is quite frustrating and time-consuming. Not sure if there is a way around this? -https://cucumber.io/blog/2017/03/07/matt-wynne-courage-and-comittment

**Comment by mattwynne** [comment]
@theo-england I fell back to a regular HTML link to do it: 71204ad19dda133d58a8c36f81aefe8c4bc7a2b3

**Pull request merged**
