### PR TITLE
Use a generic cache to wrap the GitHub API

### PR DESCRIPTION
**Pull request by mattwynne**
The cache is a YAML file on disk, which is updated from the live API by a background thread at an interval specified in the config.

We use a lock file to ensure that when puma starts multiple web
processes, only one update thread is started.

To ensure the cache is populated, we run the update once, synchronously, when the server first starts up.

@romaingweb this design is a bit different to the one we spiked, but I think it's better - we have command / query separation, and smaller objects with less responsibilities. It came out nicely from TDD. The only object using threads (the `PeriodicCall` class) is super-simple. WDYT?

### CODE REVIEW

**Comment by romaingweb** [comment]
I'm diving into this now.

**Comment by romaingweb** [comment]
This looks awesome! But the build is failing right now, unless you use a GitHub API key.
Do you have a strategy in mind to feed the tests with some cached data?

**Comment by mattwynne** [comment]
Ugh I forgot about the build TBH. We should tag out any tests from the build that need to go over the web, so yeah I guess we either need canned data or just plug in a hard-coded stub again.

> On 20 Nov 2015, at 03:56, Romain Gérard notifications@github.com wrote:
> 
> This looks awesome! But the build is failing right now, unless you use a GitHub API key.
> Do you have a strategy in mind to feed the tests with some cached data?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cucumber/website/pull/89#issuecomment-158117453.

cheers,
Matt

—
+44(0)7974430184
matt@cucumber.io
https://cucumber.io
https://twitter.com/mattwynne

**Comment by romaingweb** [comment]
Merged in b853e98

**Pull request closed without merging**
