### PR TITLE
Use sprockets to handle less files through the asset pipeline

### PR DESCRIPTION
**Pull request by romaingweb**
While switching from asset-pack to asset-pipeline we reduced the amount of the work the server has to do to deal with assets (very much like rails).  In the meantime, we ran into some issues with _.less_ files that were not watched properly, so we introduced sprockets-less to remove the ugly hack in the main.less file (`/= depends_on something.less`).

_But_, there seems to be a little (**big/huge**) bug/missing piece in sprockets-less that prevents the use of sprockets-helpers. Which means that fonts (i.e. glyphicons) are not using the proper url, with a digest at the end, inside those _.less_ files
For that we need `font-url()`to work.

There are some options to fix this:
1. Switch the entire stylesheets to sass (sprockets-sass is working great with bootstrap-sass [bower or even the gem])
2. Improve sprockets-less to work as expected (it is actually very close to its sass counterpart in terms of codebase)
3. This PR is working as well, I copied the fonts to the public directory and included a bootstrap-sprockets.less with a hack to reference the fonts properly. (not a great option, but it can work for now, while we are working on something better)

**Bonus:** I looked at a nice sprockets port for node.js project [https://www.npmjs.com/package/mincer]

### CODE REVIEW

**Comment by jbpros** [comment]
The problem would affect images, should we use sprocket helpers for them in less, right?

It'd be nice to fix it at some point but it's not vital and I say: ship it!

**Comment by mattwynne** [comment]
FWIW, my friend @rachelandrew says [you hardly need CSS pre-processors these days](https://twitter.com/rachelandrew/status/579262046048530432).

**Comment by romaingweb** [comment]
It is still very convenient. Nesting the rules, using functions etc.  Customising bootstrap is also easier with the .less/.scss version of it.

**Comment by jbpros** [comment]
@mattwynne is that what she's saying there? ;) I understand: "_start_ with HTML/CSS, do not necessarily use them". Preprocessors have advantages (e.g. taking care of vendor prefixes for you, in an up-to-date fashion (as long as you keep the preprocessor up-to-date), keeping your source files clean of them).

**Comment by mattwynne** [comment]
I dunno, if Rachel has time perhaps she'll enlighten us. She's a purist :)

**Comment by rachelandrew** [comment]
Hey! Please don't quote me out of context. I've never described myself as a "purist" either. If you are interested in my thoughts on Sass I'm moderating a free ALA online event next week on the subject. Removing myself from these notifications as I'm traveling and can live without the extra email.

**Comment by mattwynne** [comment]
- looks at shoes *

**Pull request merged**
