### PR TITLE
bdd-kickstart-exton-july-2018

### PR DESCRIPTION
**Pull request by chucksuscheck**
New public course

### CODE REVIEW

**Comment by mattwynne** [comment]
I think you need to put `---` at the end of the frontmatter (After the `dtend`)

**Comment by mattwynne** [comment]
I think the filename needs to begin `bdd` not `add` unless there's a new course I don't know about?! ;)

**Comment by mattwynne** [comment]
the file needs to have an `.md` extension to render.

**Comment by chucksuscheck** [comment]
Stupid spell corrector made bdd into add

**Comment by chucksuscheck** [comment]
I see it deployed now with an error 500.

**Comment by theo-england** [comment]
Hey @chucksuscheck I'm not super familiar with Github, but does a 500 mean there's a problem on our side or with the text? When I deploy I see the same 500 error when I try and click through to the events page.

**Pull request closed without merging**
