### PR TITLE
Add hint to microcuke

### PR DESCRIPTION
**Pull request by ghost**
Adding information from @smortex (https://gitter.im/cucumber/chat?at=56445b7efb98af9976c0bfd9) to the official cucumber website.

@aslakhellesoy Ping.

### CODE REVIEW

**Comment by maxmeyer** [comment]
@mattwynne Ping as well...

**Comment by ghost** [comment]
What about this PR? Should I merge it?

**Comment by aslakhellesoy** [comment]
Sure please do!

**Comment by ghost** [comment]
Done.

**Pull request merged**
