### PR TITLE
Ticket link and text

### PR DESCRIPTION
**Pull request by theo-england**

### CODE REVIEW

**Comment by tsundberg** [comment]
Looks like I could merge this pull request. I'm sure I shouldn't :)

As far as I can tell, the content looks good.

**Comment by mattwynne** [comment]
When I look at the preview at https://cucumber-website-pr-135.herokuapp.com/events/bdd-kickstart-stockholm-16 it's broken. I don't have time to figure out why right now. Can anyone else help?

**Comment by tsundberg** [comment]
I looked at the changes done and I think the issue is because the file Theo added is not a markdown but a slim file. I got the site up and running local and changing the file type made all the difference.

Currently not sure what would be the best way to update this pull request with an `md` instead of a `slim` file.

**Comment by tsundberg** [comment]
Updating the branch theo-england-patch-3 and looking at https://cucumber-website-pr-135.herokuapp.com/events/bdd-kickstart-stockholm-16 shows a working patch.

Please verify before merging this pull request.

**Comment by tsundberg** [comment]
Hi

Please take a look at the pull request.
I changed the file type and now I think it is ready for publishing.

Cheers,
Thomas

On Thursday, 21 April 2016, Matt Wynne notifications@github.com wrote:

> When I look at the preview at
> https://cucumber-website-pr-135.herokuapp.com/events/bdd-kickstart-stockholm-16
> it's broken. I don't have time to figure out why right now. Can anyone else
> help?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/cucumber/website/pull/135#issuecomment-213083617

## 

Thomas Sundberg
M. Sc. in Computer Science

Mobile: +46 70 767 33 15
Twitter: @thomassundberg

http://www.thinkcode.se/

Definition of done: Working software, in production.

Interested in a BDD Kickstart in Stockholm?
https://cucumber.io/events/bdd-kickstart-stockholm-16

**Comment by mattwynne** [comment]
Looks better!

At the bottom of the section [The Pledge Deal](https://cucumber-website-pr-135.herokuapp.com/events/bdd-kickstart-stockholm-16#the-pledge-deal) I see this:

a.btn-brand-blue href="https://ti.to/cucumber/bdd-kickstart-stockholm" Pledge your ticket!

Looks like maybe an indentation error? Again, no time to investigate - sorry!

**Comment by tsundberg** [comment]
I see what you mean, I'll see if I can find the time to address it.

**Comment by tsundberg** [comment]
Take a look again. 

I inlined some html in the markdown and got the blue button. Not sure if there is another way to achieve this. Please tell me if there is a better way.

**Comment by theo-england** [comment]
Thanks for the edits Thomas! Looks good on the heroku app. I've activated the payment page so it links correctly too. 

It's saying all checks have failed on github - I guess that means it won't pass? I'm a novice on github so apologies if there is an obvious solution!

**Comment by tsundberg** [comment]
Hi!

I noticed the failure as well. I looked at the error and couldn't
understand the issue. Something wasn't possible to load. Running the same
command local passed.

I'll see if I can trigger a new execution and inspect the result. Hang on!

On 25 April 2016 at 17:22, Theo notifications@github.com wrote:

> Thanks for the edits Thomas! Looks good on the heroku app. I've activated
> the payment page so it links correctly too.
> 
> It's saying all checks have failed on github - I guess that means it won't
> pass? I'm a novice on github so apologies if there is an obvious solution!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/cucumber/website/pull/135#issuecomment-214390508

## 

Thomas Sundberg
M. Sc. in Computer Science

Mobile: +46 70 767 33 15
Twitter: @thomassundberg

http://www.thinkcode.se/

Definition of done: Working software, in production.

Interested in a BDD Kickstart in Stockholm?
https://cucumber.io/events/bdd-kickstart-stockholm-16

**Comment by tsundberg** [comment]
And now all checks passed. I'm unsure what the difference is, but I will merge this pull request now.

**Pull request merged**
