### PR TITLE
Add announcement for aruba 0.10.0

### PR DESCRIPTION
**Pull request by ghost**
@aslakhellesoy @mattwynne Ping. Also announced on http://www.rubyflow.com/p/dmeya1-aruba-0100-released and on https://groups.google.com/forum/#!forum/cukes.

@aslakhellesoy Is this forum moderated? It takes a long time until posts appear there.

### CODE REVIEW

**Comment by ghost** [comment]
@aslakhellesoy Can you put me on the liste of allowed writers on cukes google channel?

**Comment by aslakhellesoy** [comment]
Done. I deleted your first pending message and let the 2nd one through (they were very similar). You can post forever now.

**Comment by ghost** [comment]
@aslakhellesoy Thanks. I didn't see the "moderated hint" from google the first time. That's why I tried it again.

**Comment by ghost** [comment]
Can anyone of you two change the [description](https://github.com/cucumber/aruba/) of aruba on Github? It would be great if it would be "Extension for popular TDD and BDD frameworks like "Cucumber", "RSpec" and "Minitest" to make testing of commandline applications meaningful, easy and fun." instead of just "CLI Steps for Cucumber". Nowadays it's more that just "cli steps". Thanks.

**Comment by aslakhellesoy** [comment]
Done! Changed it to "Test command-line applications with Cucumber-Ruby, RSpec or Minitest"

**Comment by ghost** [comment]
:-) Thanks.

**Pull request merged**
