### PR TITLE
[WIP] Add CukeUp AU videos

### PR DESCRIPTION
**Pull request by mattwynne**
TODO:
- [x] @theoengland add draft blog post
- [x] Move promo video up to the header / intro text 
- [x] Add synopsis to each talk
- [x] Make sure each talk has a URL (anchor links are enough)
- [x] Style the page (@romaingweb can you help with this please?)
- [x] Share buttons for each video to make it easy for people to share them on twitter etc.

### CODE REVIEW

**Comment by mattwynne** [comment]
@romaingweb for styling, I think we just need to use _some_ markup for each video - headings for the title / speaker / abstract, widen the videos to use all the width, etc.

I'd rather you did this than have me fiddling about with it. We decided to use a blog post for now rather than building more infrastructure for a whole `/videos` section of the site, but this can act as a HTML prototype for how that would look / feel.

**Comment by romaingweb** [comment]
@mattwynne What do you mean by: Make sure each talk has a URL (anchor links are enough)?

**Comment by theo-england** [comment]
@romaingweb Re your comment to Matt. We want to each talk to be easily linked to on Twitter, so folks can link directly to the talk they are interested in.

**Comment by romaingweb** [comment]
Is there something I can use on wistia's side?

**Comment by theo-england** [comment]
There appears to be social share buttons that I can put in after anchor links are created. But I don't think there's a way to create anchor links via wistia.

**Comment by romaingweb** [comment]
Do you how I can get access to wistia and check their options for sharing and embedding videos?

**Comment by aslakhellesoy** [comment]
Can you access the "accounts" google spreadsheetand find the login info? It's the usual password.

**Comment by mattwynne** [comment]
@romaingweb I think it's important that each talk has a URL on our site - a cucumber.io URL, not a wystia.com URL, so that inbound traffic from Twitter sharing etc comes to us.

I was hoping that just adding a header for each talk would do it - there used to be some javascript that added anchors to each header automatically - but I tried and that didn't work.

**Comment by romaingweb** [comment]
Ok, I'm going to check that javascript thingy, can you give me a hint on where I can find it?

**Comment by aslakhellesoy** [comment]
Every Markdown header (`#`, `##`, `###`) is automatically assigned a dom id when the HTML is rendered. That id can be used as an anchor.

For example `## Installation` can be linked to with https://cucumber.io/docs#installation

Is this what you mean?

I don't think using JavaScript for this is the right thing to do.

**Comment by mattwynne** [comment]
That's what I mean Askak yes. Sorry for creating confusion by guessing it was implemented in JavaScript.

**Comment by romaingweb** [comment]
Closed in c1d3f43

**Pull request closed without merging**
