### PR TITLE
Release of aruba 0.13.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@aslakhellesoy Would it be possible to automate things, say "push" articles to the cuke mailing list which have a special tag? When one of you releases a new version of the site?

**Comment by mattwynne** [comment]
@dg-ratiodata everything is possible if someone puts in the hours! Are you volunteering to do it? :+1:

What we can do is give you the commit bit on this repo so you can merge your own posts. That way you can maybe just reference the blog post in a mail to the list.

**Comment by ghost** [comment]
> What we can do is give you the commit bit on this repo so you can merge your own posts. That way you can maybe just reference the blog post in a mail to the list.

That would be great and enough for me. :-) Thanks.

**Comment by ghost** [comment]
Anything else I need to know? How is the site deployed, or did you automate that bit?

**Comment by mattwynne** [comment]
Yes, [CI](https://circleci.com/gh/cucumber/website/tree/master) deploys to production.

**Comment by ghost** [comment]
Ok.

**Comment by ghost** [comment]
@mattwynne Is it possible, that you gave me push access to "all" cucumber repos?

I wonder why I'm watching now quite a few cucumber projects. I suppose it's the `"auto"-watch feature when gettting push access` which made my account subscribe to all repos.

Although I'm grateful for the trust :-)  Is this intended?

Cheers,
Dennis

**Comment by mattwynne** [comment]
Yep, we trust you - we can always revert your changes if you make a mistake or go crazy on us!

**Comment by ghost** [comment]
Thanks! :-)

**Pull request merged**
