### PR TITLE
updated Gherkin.md

### PR DESCRIPTION
**Pull request by ShankarGarg**
Detailed description for following have been added:
1. Gherkin Characteristics 
2. Feature
3. Scenario
4, Steps: Given, When and Then

Formatting also taken care this time.

### CODE REVIEW

**Comment by jbpros** [comment]
Thanks @shnakeygarg for submitting again here (from https://github.com/cucumber/cucumber.github.com/pull/54) :)

**Comment by ShankarGarg** [comment]
When do we plan to merge this pull?

**Comment by jbpros** [comment]
I have no idea yet, I'd like @aslakhellesoy and/or @mattwynne to chime in.

I think this is a great start for improving the Gherkin documentation. There are a few inaccuracies that I'd like to point out. 

Overall, the repetitive bullet lists seem a bit dull, imo. We could still keep a concise list of rules for each gherkin element but I think some less formal explanations would make the whole thing more pleasant to read.

**Comment by ShankarGarg** [comment]
So aprt from structural changes about list and redundant explanations, is
there anything which is wrong in concept also?
I would make that change on priority.

**Comment by ShankarGarg** [comment]
removed list from Steps, Given, When and Then. Also removed/shortened information as per @jbpros comment. Let me know if this still needs refinement.

**Comment by mattwynne** [comment]
closing due to age.

**Pull request closed without merging**
