### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by romaingweb**
- [x] Put real events/news in the carousel
- [x] Make the carousel work (JS)
- [x] Learn about Behaviour-Driven Development copy
- [x] Redo artwork about BDD (credit Paul)
- [x] Team section copy (@mattwynne)
- [x] Fix link styling in `props` section
- [x] Change newsletter links to http://eepurl.com/HFz5n. 
- [x] Change Kushang's quote profile picture to attached photo (see conversation further down).

### CODE REVIEW

**Comment by paulrayner** [comment]
I sent electronic copies of the BDD flow diagram(s) to Matt. You are free to use either or both and adapt, if you attribute them to me. I think I'm asking for something like a Creative Commons Attribution ShareAlike license - right? Hope this helps! :+1:

**Comment by theo-england** [comment]
landscape_master_logo_rgb

OpenBet logo

**Comment by theo-england** [comment]
typeform_icon1_l
typeform_logo1

We can use either Typeform logo

**Comment by mattwynne** [comment]
Thanks Paul!

> On 19 Jan 2016, at 04:46, Paul Rayner notifications@github.com wrote:
> 
> I sent electronic copies of the BDD flow diagram(s) to Matt. You are free to use either or both and adapt, if you attribute them to me. I think I'm asking for something like a Creative Commons Attribution ShareAlike license - right? Hope this helps! 
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/cucumber/website/pull/96#issuecomment-172735765.

cheers,
Matt

—
+44(0)7974430184
matt@cucumber.io
https://cucumber.io
https://twitter.com/mattwynne

## 

The Cucumber logo is the intellectual property of Cucumber Ltd, a limited 
company registered in Scotland, number 456793.

UK Headquarters: Cucumber Ltd, Drumsyniebeg, Lochgoilhead, Cairndow, 
Argyll, PA24 8AN UK.

CONFIDENTIALITY NOTICE: The information in this e-mail is confidential and 
privileged; it is intended for use solely by the individual or entity named 
as the recipient hereof. Disclosure, copying, distribution, or use of the 
contents of this e-mail by persons other than the intended recipient is 
strictly prohibited and may violate applicable laws. If you have received 
this e-mail in error, please delete the original message and notify us by 
email immediately. Thank you. Cucumber Ltd.

**Comment by theo-england** [comment]
Slight edit to Kushang's quote w/ attached photo. 

"Cucumber made things more concrete and collaborative. We gained a lot of confidence in what we ship. Bugs and regressions are much less frequent than before and this saves us a lot of time and money. We are getting faster and faster to deliver" - Kushang Gajjar, PayPal

photo copy

**Comment by theo-england** [comment]
ustwo have said we can upload their logo. Github doesn't support AI format, so I've 'slacked' the image to Romain.

**Comment by romaingweb** [comment]
@theo-england done!

**Pull request merged**
