### PR TITLE
Add Cucumber Events API blog post.

### PR DESCRIPTION
**Pull request by tooky**
There's also a commit adding me as an author.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Awesome stuff @tooky !!

I've been workkng on an in-browser html formatter that would work perfectly about this. Let's catch up on slack to discuss. I also want to discusd how this fits into the greater Cucumber ecosystem.

**Comment by tooky** [comment]
@aslakhellesoy it would be really cool to try and hook this up to a fuller formatter! Exactly how we share this across implementations we can decide, but perhaps a simple binary that people can install to run the server/subscriber for the front-end that is common to all the implementations, with native publishers?

**Comment by mattwynne** [comment]
Yay! So happy to see this idea taking shape. I'd love us to be able to bundle this in with 3.0

**Comment by aslakhellesoy** [comment]
We'll do some show and tell today or tomorrow here in Edinburgh I reckon!

Most of shouldn't go into Cucumber-Ruby - it should be a standalone thing that all Cucumber impls can use.

**Pull request merged**
